import { Box, Typography, Grid} from "@mui/material";

import { useContext } from 'react';

import { useTheme } from '@mui/material/styles'
import { tokens } from '../../../util/theme.js'
import { LanguageContext } from '../../../util/lang.js'
import projects from "../../../data/projects.js";

import {A} from "../../../util/shortlink.jsx"
import PicHeader from "./sections/picHeader.jsx";

const projectLProps = (lang, c) => ({
    ...(lang === 'en' ? {  
        introTitle: 'Tiny motors, huge learning',
        intro: (<>
            This project was a portable test bench designed to measure the thrust curve 
            of small rocket motors with thrust below 200 N. It was primarily used to test 
            the mini-rocket engines from ITA Rocket Design during new member training, 
            helping assess motor performance and gather critical data for flight prediction.
            <br/><br/>
            The bench frame was built using 2020 aluminum V-slot bars, assembled with bolts 
            and nuts. This made it lightweight and easily transportable. The motor is mounted 
            on a 3D-printed cart that slides along two steel rods using linear bearings. 
            Thrust generated by the motor is transferred to a 200 N load cell for measurement. 

            Regarding the electronics, an ADS1256 module acquires the load cell readings, 
            which are processed by an ESP32 before being sent via USB to a computer. The 
            computer runs a Python script to log the data and display it in real time.
        </>),
        presTitle: 'Presented at Contecc',
        pres: (<>
            After building the bench and successfully using it to test both commercial C6-5 motors and the custom-built ITA Rocket 
            Design motors, we recognized the potential of our setup to support other student teams and independent groups involved 
            in rocketry. With that in mind, we decided to make our project open and accessible, hoping it could serve as a useful 
            resource for others working on similar propulsion systems or educational rocketry initiatives.
            <br/><br/>
            In this context, I coauthored, together with Raphael Fernandes de Oliveira, the paper 
            <A c={c} href={"https://www.confea.org.br/midias/uploads-imce/contecc%202024/MEC/" +
            "BANCADA_PORT%C3%81TIL_E_DE_BAIXO_CUSTO_PARA_ENSAIO_DE_PEQUENOS_MOTORES-FOGUETE.pdf"}>
            Bancada Portátil e de Baixo Custo para Ensaio de Pequenos Motores-Foguete</A>, which was among the 24 papers selected 
            for oral presentation at the 2024 edition of <A c={c} href="https://www.soea.org.br/">SOEA</A>, during the 79th edition 
            of the conference. Presenting our work at such a prominent national engineering event was an incredible experience. 
            It allowed us to share our design choices, lessons learned, and the technical insights gained throughout the project.
            <br/><br/>
            Currently, I am working on a new iteration of the test bench. This version aims to improve usability through a more 
            intuitive interface. I'm planning to include live visualization, easier calibration routines, and possibly support 
            for additional sensor types. This new version will be released 
            as an open-source project on GitHub, so stay tuned—there's more to come soon!
        </>),
    } : {
        introTitle: 'Pequenos motores, grande aprendizado',
        intro: (<>
            Este projeto consistiu em uma bancada portátil para medir a curva de empuxo de pequenos 
            motores-foguete com empuxo inferior a 200 N. Foi utilizada principalmente para testar 
            os motores dos minifoguetes do ITA Rocket Design durante o treinamento de novos membros, 
            auxiliando na verificação do desempenho dos motores e na aquisição de dados críticos 
            para a previsão do voo.
            <br/><br/>
            A estrutura da bancada foi feita com perfis de alumínio 2020 tipo V-slot, fixados com 
            parafusos e porcas. Isso a tornou muito leve e fácil de transportar. O motor é fixado 
            em um suporte impresso em 3D que desliza sobre dois eixos de aço com mancais lineares, 
            transmitindo a força da combustão para uma célula de carga de 200 N.
            Quanto à eletrônica da bancada, um ADS1256 realiza a aquisição dos dados da célula de 
            carga, que são processados por um ESP32 antes de serem enviados para um computador via 
            USB. O computador executa um software em Python para registrar os dados e 
            exibi-los em tempo real.
        </>),
        presTitle: 'Apresentado no Contecc',
        pres: (<>
            Após construir a bancada e utilizá-la com sucesso para testar tanto motores comerciais 
            C6-5 quanto os motores desenvolvidos pela ITA Rocket Design, percebemos o potencial 
            do projeto para apoiar outras equipes estudantis e grupos independentes envolvidos com 
            foguetemodelismo. Pensando nisso, decidimos tornar o projeto aberto e acessível, com 
            a intenção de que ele pudesse servir como uma ferramenta útil para quem trabalha com sistemas 
            de propulsão semelhantes ou participa de iniciativas educacionais na área.
            <br/><br/>
            Nesse sentido, escrevi, juntamente com Raphael Fernandes de Oliveira, o artigo 
            <A c={c} href={"https://www.confea.org.br/midias/uploads-imce/contecc%202024/MEC/" +
            "BANCADA_PORT%C3%81TIL_E_DE_BAIXO_CUSTO_PARA_ENSAIO_DE_PEQUENOS_MOTORES-FOGUETE.pdf"}>
            Bancada Portátil e de Baixo Custo para Ensaio de Pequenos Motores-Foguete</A>, que foi 
            um dos 24 trabalhos selecionados para apresentação oral no Contecc 2024, durante a 79ª 
            edição da <A c={c} href="https://www.soea.org.br/">SOEA</A>. Foi uma experiência incrível 
            apresentar nosso trabalho em um evento nacional de grande relevância, onde pudemos 
            compartilhar nossas escolhas de projeto, os aprendizados acumulados e as soluções 
            técnicas adotadas.
            <br/><br/>
            Atualmente, estou desenvolvendo uma nova versão da bancada de testes, com foco em uma 
            interface mais amigável ao usuário. Estou planejando incluir visualização de dados em 
            tempo real, rotinas de calibração mais simples e, possivelmente, suporte a diferentes 
            tipos de sensores. Este novo projeto será lançado de forma aberta no GitHub — então 
            fique de olho, pois em breve teremos novidades!
        </>),
    })
})

export default function TestBenchPage() {
    const {lang} = useContext(LanguageContext)
    const theme = useTheme()
    const colors = tokens(theme.palette.mode)
    const lProps = projectLProps(lang, colors)
        
    const proj = projects.find(project => 
    project.title.toLowerCase() === 'test bench')
    return(
    <>
        <PicHeader 
        cover = '2-5.webp' 
        title={proj.title}
        subtitle={proj.subtitle[lang]}
        tech={proj.tech}
        />
    
        {/* Details */}
        <Grid container spacing={4} mt='30px'>
            <Grid size={{xs:12, sm:12,md:12,lg:6}}
            alignContent='center'>
                <Box component='img' 
                alt='motor burning at bench'
                src='/images/2-2.webp'
                width= {`${(100/(3500/2304 + 911/864) * 911/864).toPrecision(4)}%`}
                sx={{
                    borderRadius: '10px 0 0 10px',
                    borderLeft: '1.5px solid ' + colors.grey[900],
                    borderTop: '1.5px solid ' + colors.grey[900],
                    borderBottom: '1.5px solid ' + colors.grey[900],
                }}
                />
                <Box component='img' 
                alt='test bench'
                src='/images/2-4.webp'
                width= {`${(100/(3500/2304 + 911/864) * 3500/2304).toPrecision(4)}%`}
                sx={{
                    borderRadius: '0 10px 10px 0',
                    borderRight: '1.5px solid ' + colors.grey[900],
                    borderTop: '1.5px solid ' + colors.grey[900],
                    borderBottom: '1.5px solid ' + colors.grey[900],
                }}
                />
            </Grid>
            <Grid size={{xs:12, sm:12,md:12,lg:6}}>
                <Typography variant="h2" gutterBottom>{lProps.introTitle}</Typography>
                <Typography variant='body2' textAlign='justify'>
                    {lProps.intro}
                </Typography>
            </Grid>
            <Grid size={{xs:12, sm:12,md:12,lg:6}}>
                <Typography variant="h2" textAlign='right' gutterBottom>{lProps.presTitle}</Typography>
                <Typography variant='body2' textAlign='justify'>
                    {lProps.pres}
                </Typography>
            </Grid>
            <Grid size={{xs:12, sm:12,md:12,lg:6}}
            alignContent='center'>
                <Box component='img' 
                alt='presenting at contecc'
                src='/images/2-6.webp'
                width= {`${(100/(3/4 + 466/352) * 3/4).toPrecision(4)}%`}
                sx={{
                    borderRadius: '10px 0 0 10px',
                    borderLeft: '1.5px solid ' + colors.grey[900],
                    borderTop: '1.5px solid ' + colors.grey[900],
                    borderBottom: '1.5px solid ' + colors.grey[900],
                }}
                />
                <Box component='img' 
                alt='test bench CAD'
                src='/images/2.webp'
                width= {`${(100/(3/4 + 466/352) * 466/352).toPrecision(4)}%`}
                sx={{
                    borderRadius: '0 10px 10px 0',
                    borderRight: '1.5px solid ' + colors.grey[900],
                    borderTop: '1.5px solid ' + colors.grey[900],
                    borderBottom: '1.5px solid ' + colors.grey[900],
                }}
                />
            </Grid>
        </Grid>
    </>
)}