name: Deploy to EC2 via SSM

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy from GitHub Actions" \
          --parameters commands=["cd /home/ubuntu/Personal-Website","git pull","npm install --omit=dev","npm run build","sudo systemctl restart pw.service"] \
          --region ${{ secrets.AWS_REGION }}
